#!/bin/bash

# ===========================================
# ALOO - First Time Setup Script
# ===========================================
# This script handles everything needed to get started:
# 1. Check prerequisites
# 2. Install dependencies
# 3. Generate environment file with secrets
# 4. Setup database (SQLite or PostgreSQL)
# 5. Create first user
# ===========================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

print_step() {
    echo -e "\n${BLUE}==>${NC} $1"
}

print_success() {
    echo -e "${GREEN}✓${NC} $1"
}

print_warning() {
    echo -e "${YELLOW}⚠${NC} $1"
}

print_error() {
    echo -e "${RED}✗${NC} $1"
}

# Generate a random secret
generate_secret() {
    openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64
}

echo ""
echo "  ___  _    ___   ___  "
echo " / _ \| |  / _ \ / _ \ "
echo "| |_| | |_| |_| | |_| |"
echo "|_/ |_|____\___/ \___/ "
echo ""
echo "Lead Generation CRM - Setup"
echo "============================"

# ===========================================
# Step 1: Check Prerequisites
# ===========================================
print_step "Checking prerequisites..."

# Check Node.js
if ! command -v node &> /dev/null; then
    print_error "Node.js is not installed. Please install Node.js 18+ first."
    exit 1
fi

NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1)
if [ "$NODE_VERSION" -lt 18 ]; then
    print_error "Node.js 18+ required. You have $(node -v)"
    exit 1
fi
print_success "Node.js $(node -v)"

# Check npm
if ! command -v npm &> /dev/null; then
    print_error "npm is not installed."
    exit 1
fi
print_success "npm $(npm -v)"

# Check if Docker is available (optional)
DOCKER_AVAILABLE=false
if command -v docker &> /dev/null; then
    if docker info &> /dev/null; then
        DOCKER_AVAILABLE=true
        print_success "Docker available"
    else
        print_warning "Docker installed but not running"
    fi
else
    print_warning "Docker not installed (SQLite will be used)"
fi

# ===========================================
# Step 2: Install Dependencies
# ===========================================
print_step "Installing dependencies..."

npm install --silent
print_success "Dependencies installed"

# ===========================================
# Step 3: Database Selection
# ===========================================
print_step "Database setup..."

if [ "$DOCKER_AVAILABLE" = true ]; then
    echo ""
    echo "Choose your database:"
    echo "  1) SQLite (simple, no Docker needed, great for testing)"
    echo "  2) PostgreSQL (production-ready, requires Docker)"
    echo ""
    read -p "Enter choice [1]: " DB_CHOICE
    DB_CHOICE=${DB_CHOICE:-1}
else
    echo "Docker not available - using SQLite"
    DB_CHOICE=1
fi

# ===========================================
# Step 4: Generate Environment File
# ===========================================
print_step "Generating environment file..."

if [ -f .env ]; then
    print_warning ".env already exists"
    read -p "Overwrite? [y/N]: " OVERWRITE
    if [ "$OVERWRITE" != "y" ] && [ "$OVERWRITE" != "Y" ]; then
        print_warning "Keeping existing .env"
    else
        rm .env
    fi
fi

if [ ! -f .env ]; then
    # Generate secrets
    NEXTAUTH_SECRET=$(generate_secret)
    ADMIN_SECRET=$(generate_secret)
    ENCRYPTION_SECRET=$(generate_secret)

    if [ "$DB_CHOICE" = "2" ]; then
        # PostgreSQL
        DATABASE_URL="postgresql://postgres:postgres@localhost:5433/aloo"
        DB_PROVIDER="postgresql"
    else
        # SQLite
        DATABASE_URL="file:./data/aloo.db"
        DB_PROVIDER="sqlite"
    fi

    cat > .env << EOF
# ===========================================
# ALOO Environment Configuration
# Generated by setup script on $(date)
# ===========================================

# Database
DATABASE_URL="${DATABASE_URL}"
DB_PROVIDER="${DB_PROVIDER}"

# NextAuth
NEXTAUTH_SECRET="${NEXTAUTH_SECRET}"
NEXTAUTH_URL="http://localhost:3000"

# Admin Secret - for creating users via /admin
ADMIN_SECRET="${ADMIN_SECRET}"

# Encryption Secret - for API key storage
ENCRYPTION_SECRET="${ENCRYPTION_SECRET}"

# ===========================================
# Optional: External APIs
# ===========================================
# RAPIDAPI_KEY="your-rapidapi-key"
EOF

    print_success "Environment file created with auto-generated secrets"
fi

# ===========================================
# Step 5: Setup Database
# ===========================================
print_step "Setting up database..."

if [ "$DB_CHOICE" = "2" ]; then
    # PostgreSQL with Docker
    print_step "Starting PostgreSQL container..."
    docker compose up -d postgres

    echo "Waiting for PostgreSQL to be ready..."
    sleep 3

    # Wait for healthy state
    for i in {1..30}; do
        if docker compose exec -T postgres pg_isready -U postgres -d aloo &> /dev/null; then
            break
        fi
        sleep 1
    done
    print_success "PostgreSQL is running"
else
    # SQLite - create data directory
    mkdir -p data
    print_success "SQLite data directory created"
fi

# Generate Prisma client and run migrations
print_step "Running database migrations..."
npm run db:generate --silent
npm run db:push --silent 2>/dev/null || npm run db:migrate --silent
print_success "Database schema applied"

# ===========================================
# Step 6: Create Default User
# ===========================================
print_step "Creating default admin user..."

# Create default user via tsx (ESM compatible)
npx tsx -e "
import { PrismaClient } from './src/generated/prisma/client.js';
import { PrismaBetterSqlite3 } from '@prisma/adapter-better-sqlite3';
import bcrypt from 'bcrypt';

const filePath = process.env.DATABASE_URL.replace('file:', '');
const adapter = new PrismaBetterSqlite3({ url: filePath });
const prisma = new PrismaClient({ adapter });

async function createDefaultUser() {
  try {
    const existing = await prisma.user.findUnique({ where: { email: 'admin@aloo.com' } });
    if (!existing) {
      const hash = await bcrypt.hash('admin', 10);
      await prisma.user.create({
        data: {
          email: 'admin@aloo.com',
          name: 'Admin',
          password: hash,
          createdAt: new Date()
        }
      });
      console.log('created');
    } else {
      console.log('exists');
    }
  } finally {
    await prisma.\$disconnect();
  }
}
createDefaultUser();
" 2>/dev/null && print_success "Default user created" || print_warning "Could not create default user"

# ===========================================
# Done!
# ===========================================
echo ""
echo -e "${GREEN}=========================================${NC}"
echo -e "${GREEN}  Setup Complete!${NC}"
echo -e "${GREEN}=========================================${NC}"
echo ""
echo "Start the development server:"
echo -e "  ${BLUE}npm run dev${NC}"
echo ""
echo "Then open: http://localhost:3000"
echo ""
echo -e "${YELLOW}Default Login:${NC}"
echo "  Email:    admin@aloo.com"
echo "  Password: admin"
echo ""

if [ "$DB_CHOICE" = "2" ]; then
    echo "Database: PostgreSQL (Docker)"
    echo "  Stop:  docker compose down"
    echo "  Start: docker compose up -d postgres"
else
    echo "Database: SQLite (data/aloo.db)"
fi

echo ""
echo "Useful commands:"
echo "  npm run db:studio  - Open database GUI"
echo "  npm run setup:user - Create/update users"
echo ""
